USE master
GO

--IF DB_ID('AthenasDB') IS NOT NULL
--	DROP DATABASE AthenasDB
--GO

--CREATE DATABASE AthenasDB
--GO

USE AthenasDB
GO


/*
	TABLA CATEGORIA DONDE SE ESPECIFICAN LAS CATEGORIAS DE CADA PRODUCTO
*/
IF OBJECT_ID('Categoria') IS NOT NULL
	DROP TABLE Categoria
GO

CREATE TABLE Categoria(
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Descripcion VARCHAR(50) NOT NULL,
	Activo CHAR(1) NULL
)
GO

/*
	TABLA PRODUCTO
*/
IF OBJECT_ID('Producto') IS NOT NULL
	DROP TABLE Producto
GO


CREATE TABLE Producto (
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Descripcion VARCHAR(50) NOT NULL,
	PrecioCompra DECIMAL(10,2) NOT NULL,
	PrecioVenta DECIMAL(10,2) NOT NULL,
	StockActual INT NOT NULL,
	StockMin INT NULL DEFAULT NULL,
	CategoriaId INT NOT NULL,
	Imagen VARCHAR(255) NULL DEFAULT 'NOIMAGE.jpg',
	Activo CHAR(1) NULL DEFAULT '1',
	CONSTRAINT FK_Producto_Categoria FOREIGN KEY (CategoriaId) REFERENCES Categoria (Id)
)
go

/*
	TABLA CLIENTE
*/
IF OBJECT_ID('Cliente') IS NOT NULL
	DROP TABLE Cliente
GO

CREATE TABLE Cliente (
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Nombre VARCHAR(100) NOT NULL ,
	Apellido VARCHAR(100) NOT NULL ,
	Telefono VARCHAR(15) NOT NULL,
	DNI VARCHAR(9) NOT NULL,
	Sexo CHAR(1) NOT NULL,
	FechaCreacion DATE NULL DEFAULT NULL,
	Activo CHAR(1) NULL DEFAULT '1' 
)
GO


/*
	TABLA PROVEEDOR
*/
IF OBJECT_ID('Proveedor') IS NOT NULL
	DROP TABLE Proveedor
GO

CREATE TABLE Proveedor (
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	RzSocial VARCHAR(100) NOT NULL ,
	RUC VARCHAR(20) NULL DEFAULT NULL ,
	Representante VARCHAR(100) NOT NULL ,
	Email VARCHAR(100) NULL DEFAULT NULL ,
	Telefono VARCHAR(15) NOT NULL ,
	Direccion VARCHAR(100) NOT NULL,
	Activo CHAR(1) NULL DEFAULT '1' 
)
GO



/*
	TABLA TRABAJADOR	
*/
IF OBJECT_ID('Trabajador') IS NOT NULL
	DROP TABLE Trabajador
GO

CREATE TABLE Trabajador(
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Nombre VARCHAR(100) NOT NULL,
	Apellido VARCHAR(100) NOT NULL,
	Telefono VARCHAR(15) NOT NULL,
	DNI VARCHAR(9) NOT NULL,
	Direccion VARCHAR(100) NOT NULL,
	Email VARCHAR(100),
	Usuario VARCHAR(50) NOT NULL, 
	Contrasenia VARCHAR(255) NOT NULL, -- "2a%............" -- "bcrypt"  (hash, "123") true o false | excepcion
	Sexo CHAR(1) NOT NULL,
	Rol VARCHAR(20) NOT NULL -- 
)
GO

/*
	TABLA PARA ALMACENAR LOS ESPECIFICOS DE LAS COMPRAS
*/
IF OBJECT_ID('Compra') IS NOT NULL
	DROP TABLE Compra
GO

CREATE TABLE Compra (
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ProveedorId INT NOT NULL,
	TrabajadorId INT NOT NULL,
	Fecha DATE NOT NULL,
	Estado INT NOT NULL DEFAULT '0', -- 1: Recibido, 0: Por Recibir
	Activo CHAR(1) NULL DEFAULT '1',
	CONSTRAINT FK_Compra_Proveedor FOREIGN KEY (ProveedorId) REFERENCES Proveedor (Id),
	CONSTRAINT FK_Compra_Trabajador FOREIGN KEY (TrabajadorId) REFERENCES Trabajador (Id)
)
GO

/*
	TABLA PARA ALMACENAR LOS ESPECIFICOS DE LAS COMPRAS
*/
IF OBJECT_ID('DetalleCompra') IS NOT NULL
	DROP TABLE DetalleCompra
GO

CREATE TABLE DetalleCompra (
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	CompraId INT NOT NULL,
	ProductoId INT NOT NULL,
	Cantidad INT NOT NULL,
	Precio DECIMAL(10,2) NOT NULL,
	Activo CHAR(1) NULL DEFAULT '1',
	CONSTRAINT FK_DetCompra_Compra FOREIGN KEY (CompraId) REFERENCES Compra (Id) ,
	CONSTRAINT FK_DetCompra_Producto FOREIGN KEY (ProductoId) REFERENCES Producto (Id) 
)
go
/*
	TABLA PARA ALMACENAR LOS ESPECIFICOS DE LAS VENTAS
*/
IF OBJECT_ID('Venta') IS NOT NULL
	DROP TABLE Venta 
GO 

CREATE TABLE Venta (
	Id INT NOT NULL  IDENTITY(1,1) PRIMARY KEY,
	ClienteId INT NOT NULL,
	TrabajadorId INT NOT NULL,
	Fecha DATE NOT NULL,
	DescTotal DECIMAL(10,2) NULL DEFAULT 0.00,
	Activo CHAR(1) NULL DEFAULT '1' ,
	CONSTRAINT FK_Venta_Cliente FOREIGN KEY (ClienteId) REFERENCES Cliente (Id) ,
	CONSTRAINT FK_Venta_Trabajador FOREIGN KEY (TrabajadorId) REFERENCES Trabajador (Id)
)
GO


/*
	CAMBIOS A DETALLES
*/
IF OBJECT_ID('DetalleVenta') IS NOT NULL
	DROP TABLE DetalleVenta
GO

CREATE TABLE DetalleVenta(
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	VentaId INT NOT NULL,
	ProductoId INT NOT NULL,
	Cantidad INT NOT NULL,
	Precio DECIMAL(10,2) NOT NULL,
	DesctUni DECIMAL(10,2) NULL DEFAULT 0.00,
	Activo CHAR(1) NULL DEFAULT '1' ,
	CONSTRAINT FK_DetVenta_Venta FOREIGN KEY (VentaId) REFERENCES Venta (Id),
	CONSTRAINT FK_DetVenta_Producto FOREIGN KEY (ProductoId) REFERENCES Producto (Id) 
)
GO



/*
	TABLA DE PROMOCIONES
*/
IF OBJECT_ID('Promocion') IS NOT NULL
	DROP TABLE Promocion
GO

CREATE TABLE Promocion(
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ProductoId INT NOT NULL,
	Tipo INT NOT NULL,
	Valor DECIMAL(10,2) NOT NULL,
	FechaInicio DATE NULL DEFAULT NULL,
	FechaFin DATE NULL DEFAULT NULL,
	Activo CHAR(1) NULL DEFAULT '1' ,
	CONSTRAINT FK_Promo_Producto FOREIGN KEY (ProductoId) REFERENCES Producto(Id) 
)
GO















